### ISSUE TITLE
[Proposals] "not_answered" state is not translated

### ISSUE THREAD

**Issue by hellpe** [OpenSourcePolitics/dbt-processing#58]
Can be reproduced here: https://metabase.osp.cat/question/7344-propositions-triees-par-commentaires-soutiens

Translations are in `int_proposals.sql`:

```
    (CASE
        WHEN decidim_proposals.state = 'evaluating' THEN 'En cours d''évaluation'
        WHEN decidim_proposals.state = 'rejected' THEN 'Rejetée'
        WHEN decidim_proposals.state = 'accepted' THEN 'Acceptée'
        WHEN decidim_proposals.state IS NULL THEN 'Pas d''état'
        ELSE decidim_proposals.state
        END
    ) AS translated_state
```

Official translations in Decidim: https://github.com/decidim/decidim/blob/45efdc1e82e980dc8f60ac076b7142e90226ac61/decidim-proposals/config/locales/fr.yml#L117

```
          state_eq:
            label: État
            values:
              accepted: Acceptée
              evaluating: En cours d'évaluation
              not_answered: Non répondue
              published: Publiée
              rejected: Rejetée
              validating: Validation technique
              withdrawn: Retirée
```
